const {
	APPLICATION_PORT,
	MQTT_HOST,
	MQTT_PORT,
	MONGODB_HOST,
	MONGODB_USERNAME,
	MONGODB_PASSWORD,
	MONGODB_PORT,
	MONGODB_DBNAME,
} = process.env;
export default {
	APPLICATION_PORT,
	MQTT_HOST,
	MQTT_PORT,
	MONGODB_HOST,
	MONGODB_USERNAME,
	MONGODB_PASSWORD,
	MONGODB_PORT,
	MONGODB_DBNAME,
};
